= Docs-as-Code for Open-Source Medical Hardware & PPE's
:doc-name: architecture.adoc
:revnumber: v1.0.0
:toc: left

ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-CC_BY_4.0-yellow.svg[Attribution 4.0 International (CC BY 4.0), link=https://creativecommons.org/licenses/by/4.0/]
image:https://img.shields.io/badge/Contribute%20on-GitHub-orange[Contribute on GitHub, link=https://github.com/tetrabiodistributed/docs-as-code-for-medical-oshw.git]
image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=https://tetrabiodistributed.github.io/docs-as-code-for-medical-oshw/architecture.pdf]
image:https://img.shields.io/badge/View%20-Presentation-green[Download PDF, link=https://tetrabiodistributed.github.io/docs-as-code-for-medical-oshw/presentation.html]
endif::[]

<<<

== Stakeholder Needs
 
The *Docs-as-Code for Open-Source Medical Hardware & PPE's* architecture is guided by a series of stakeholder needs, listed below.


=== 1: Quality System Processes for Medical Device Manufacturers
****
Manufacturers of medical devices shall ensure that finished devices will be safe and effective.footnote:2-21CFRPart820FDAQMSForMedicalDevices[21 CFR Part 820 — Quality System Regulation https://www.ecfr.gov/current/title-21/chapter-I/subchapter-H/part-820]footnote:3-ISO13485QualityManagementForMedicalDevices[ISO 13485 - Quality Management for Medical Devices https://www.iso.org/iso-13485-medical-devices.html]
****


=== 2: Design & Development Planning
****
Each manufacturer shall establish and maintain plans that describe or reference the design and development activities and define responsibility for implementation. The plans shall identify and describe the interfaces with different groups or activities that provide, or result in, input to the design and development process. The plans shall be reviewed, updated, and approved as design and development evolves.footnote:4-21CFRPart820dot30BDesignAndDevelopmentPlanning[21 CFR Part 820.30 (B) - Design and Development Planning https://www.ecfr.gov/current/title-21/chapter-I/subchapter-H/part-820#p-820.30(b)]
****



== Data Structures
This section covers each data structure type in the *Docs-as-Code for Open-Source Medical Hardware & PPE's* architecture.


=== Design & Development Plan
*Purpose:* Data structure for a Design & Development Plan (DDP) document

.Design & Development Plan Template
----
project_scope: {{project_scope}}
project_cost: {{project_cost}}
project_schedule: {{project_schedule}}

----

.Design & Development Plan Specification
|===
|Field |Type |Item Type |Description |Source


|project_scope
|dict

|string

|A way to set boundaries, goals, deadlines, assumptions, & constraints.

|



|project_cost
|string

|

|An amount of money needed to pay or compensate to buy or take a service or good.

|



|project_schedule
|string

|

|Establishes the criteria & activities for developing and monitoring a schedule.

|



|===


==== *Derived From:*




* xref:index.html#_2_design_development_planning[Design & Development Planning]





